name: Gradr

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: audit code style
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]
        operating-system: [ubuntu-18.04]
        php: [7.2.12]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Prepare To Install
        uses: actions/checkout@v2
        with:
          node-version: 10.x

      - name: Install Node dependencies
        run: |
          yarn install
          yarn add phplint

      - name: Run Audits
        run: yarn phplint './src/**/*.php'
  ch-1:
    needs: lint
    name: audit challenge 1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]
        operating-system: [ubuntu-18.04]
        php: [7.2.12]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Prepare to install node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install Jest and it's dependencies
        run: |
          yarn install
          yarn add jest jest-runner-phpunit babel-core babel-jest axios @actions/core @actions/github

      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v1
        with:
          php-version: "7.4"

      - name: install PHPunit and other dependencies
        run: |
          composer require --dev phpunit/phpunit
          composer require guzzlehttp/guzzle:~6.0

      - name: Prepare Audits
        uses: actions/checkout@v2
        with:
          repository: BuildforSDG-Cohort1-Assessment/covid-19-estimator-audits-php
          path: audits

      - name: Run Audits
        run: |
          ls audits
          npx jest --json --outputFile=audits/ch-1.json --noStackTrace --config=audits/config.js

      - name: Report Audit Stats
        uses: ./.github/actions/ch-1
        if: always()

  ch-2:
    needs: ch-1
    name: audit challenge 2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]
        operating-system: [ubuntu-18.04]
        php: [7.2.12]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Prepare to install node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install Jest and it's dependencies
        run: |
          yarn install
          yarn add jest jest-runner-phpunit babel-core babel-jest axios @actions/core @actions/github

      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v1
        with:
          php-version: "7.4"

      - name: install PHPunit and other dependencies
        run: |
          composer require --dev phpunit/phpunit
          composer require guzzlehttp/guzzle:~6.0

      - name: Prepare Audits
        uses: actions/checkout@v2
        with:
          repository: BuildforSDG-Cohort1-Assessment/covid-19-estimator-audits-php
          path: audits

      - name: Run Audits
        run: |
          ls audits
          npx jest --json --outputFile=audits/ch-2.json --noStackTrace --config=./config.js

      - name: Report Audit Stats
        uses: ./.github/actions/ch-2
        if: always()

  ch-3:
    needs: ch-2
    name: audit challenge 3
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]
        operating-system: [ubuntu-18.04]
        php: [7.2.12]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Prepare to install node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install Jest and it's dependencies
        run: |
          yarn install
          yarn add jest jest-runner-phpunit babel-core babel-jest axios @actions/core @actions/github

      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v1
        with:
          php-version: "7.4"

      - name: install PHPunit and other dependencies
        run: |
          composer require --dev phpunit/phpunit
          composer require guzzlehttp/guzzle:~6.0

      - name: Prepare Audits
        uses: actions/checkout@v2
        with:
          repository: BuildforSDG-Cohort1-Assessment/covid-19-estimator-audits-php
          path: audits

      - name: Run Audits
        run: |
          ls audits
          npx jest --json --outputFile=audits/ch-3.json --noStackTrace --config=./config.js

      - name: Report Audit Stats
        uses: ./.github/actions/ch-3
        if: always()
